[package]
name = "bevy_garden"
version = "0.1.0"
authors = ["Jan Reitz <jan-reitz@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy="0.4"
rand="0.8"